server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driverClassName: org.postgresql.Driver
  jooq:
    dialect: POSTGRES

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  profiles:
    active: development